Repository CHUPITO-Org/FE-Chupito, pull requests merged in 2023-11, with the labels that each got.

#35 docs: update readme file
  .env-example
  .env.example
  README.md
Labels: documentation

#40 refactor: change the way of use of environment variables and firebase parameters
  src/components/Main/Main.tsx
  src/environment/environment.js
  src/pages/Events/Events.tsx
  src/pages/EventsAdmin/EventsAdmin.tsx
  src/shared/api/backends/firebase.ts
  src/shared/api/endpoints/conferences.ts
  src/shared/environment/environment.ts
  src/shared/hooks/useAuth.tsx
Labels: refactor

#44 refactor: getting all headquarters using enpoint
  public/index.html
  src/api/headquarters.js
  src/api/roles.js
  src/api/users.js
  src/components/AttendeeForm.js
  src/components/CreateUpdateEvent.js
  src/components/CreateUpdateUser.js
  src/components/Dashboard/Headquarters.js
  src/components/DropDown/SelectWithLoading.tsx
  src/components/DropDown/stories/SelectWithLoading.stories.tsx
  src/components/Event.js
  src/components/EventEditView/EventEditView.spec.tsx
  src/components/EventEditView/EventEditView.tsx
  src/components/EventView/EventView.spec.tsx
  src/components/EventView/EventView.tsx
  src/components/EventView/stories/EventView.stories.tsx
  src/components/EventsAdminView/EventAdminView.spec.tsx
  src/components/EventsAdminView/EventAdminView.tsx
  src/components/EventsView/EventsView.spec.tsx
  src/components/EventsView/EventsView.tsx
  src/components/EventsView/stories/EventsView.stories.tsx
  src/components/ExportAttendees.js
  src/components/Headquarters/Headquarters.spec.tsx
  src/components/Headquarters/Headquarters.tsx
  src/components/Profile/ChangePassword.js
  src/components/UserForm/stories/UserForm.stories.tsx
  src/components/Users.js
  src/database/dataService.js
  src/database/database.js
  src/mocks/headquarter.js
  src/mocks/tags.js
  src/pages/EventInfo/EventInfo.tsx
  src/pages/Events/Events.tsx
  src/pages/EventsAdmin/EventsAdmin.tsx
  src/pages/Login/Login.tsx
  src/shared/api/baseRequest.js
  src/shared/api/endpoints/attendees.js
  src/shared/api/endpoints/base.ts
  src/shared/api/endpoints/conferences.spec.ts
  src/shared/api/endpoints/conferences.ts
  src/shared/api/endpoints/events.js
  src/shared/api/endpoints/headquarters.spec.ts
  src/shared/api/endpoints/headquarters.ts
  src/shared/api/endpoints/images.js
  src/shared/api/endpoints/roles.spec.ts
  src/shared/api/endpoints/roles.ts
  src/shared/api/endpoints/security.js
  src/shared/api/endpoints/users.spec.ts
  src/shared/api/endpoints/users.ts
  src/shared/api/index.ts
  src/shared/contexts/Auth/AuthProvider.tsx
  src/shared/entities/headquarter.ts
  src/shared/entities/tag.ts
  src/shared/entities/user.ts
  src/utils/logout.ts
Labels: refactor

#47 refactor: login page and validation
  .env.example
  .gitignore
  README.md
  src/App.test.js
  src/components/EventCard/EventCard.spec.tsx
  src/components/EventCard/EventCard.tsx
  src/components/EventEditView/EventEditView.spec.tsx
  src/components/EventEditView/EventEditView.tsx
  src/components/EventView/EventView.spec.tsx
  src/components/EventView/EventView.tsx
  src/components/EventsView/EventsView.spec.tsx
  src/components/EventsView/EventsView.tsx
  src/components/Login/Login.spec.tsx
  src/components/Login/Login.tsx
  src/pages/Event/Event.tsx
  src/pages/EventEdit/EventEdit.spec.tsx
  src/pages/EventEdit/EventEdit.tsx
  src/pages/Login/Login.tsx
  src/shared/api/backends/firebase.ts
  src/shared/api/endpoints/authentication.ts
  src/shared/entities/conference.ts
  src/shared/environment/environment.ts
Labels: enhancement, refactor

#48 feat: integrate dockerfile to create frontend images
  .dockerignore
  .nginx/default.conf
  Dockerfile
  Makefile
  README.md
Labels: enhancement

#49 refactor: removed unused environment variables and all unit tests
  .env.example
  src/components/AppBarMobile/AppBarMobile.spec.tsx
  src/components/AppBarMobile/AppBarMobile.spec.tsx.txt
  src/components/AppBarMobile/AppBarMobile.tsx
  src/components/AppBarWeb/AppBarWeb.spec.tsx
  src/components/AppBarWeb/AppBarWeb.spec.tsx.txt
  src/components/AppBarWeb/AppBarWeb.tsx
  src/components/AppRoutes/AppRoutes.spec.tsx
  src/components/AppRoutes/AppRoutes.spec.tsx.txt
  src/components/AppRoutes/AppRoutes.tsx
  src/components/EventCard/EventCard.spec.tsx
  src/components/EventCard/EventCard.tsx
  src/components/EventCard/stories/EventCard.stories.tsx
  src/components/EventView/stories/EventView.stories.tsx
  src/components/EventsAdminView/EventAdminView.spec.tsx
  src/components/EventsAdminView/EventAdminView.tsx
  src/components/EventsView/stories/EventsView.stories.tsx
  src/components/Login/Login.spec.tsx
  src/components/Login/Login.tsx
  src/components/Main/Main.spec.tsx
  src/components/Main/Main.tsx
  src/pages/Event/Event.tsx
  src/pages/EventEdit/EventEdit.tsx
  src/pages/EventInfo/EventInfo.spec.tsx.txt
  src/pages/EventInfo/EventInfo.tsx
  src/pages/Events/Events.tsx
  src/pages/EventsAdmin/EventsAdmin.spec.tsx.txt
  src/pages/Login/Login.tsx
  src/shared/api/baseRequest.js
  src/shared/api/baseRequest.ts
  src/shared/api/endpoints/conferences.spec.ts
  src/shared/api/endpoints/events.js
  src/shared/api/endpoints/events.ts
  src/shared/api/endpoints/security.js
  src/shared/api/endpoints/security.ts
  src/shared/entities/props/eventsAdminViewProps.ts
  src/utils/logout.ts
Labels: bug, refactor

#50 ci: implement pipeline to build and publish FE image
  .github/workflows/build_and_publish.yml
Labels: enhancement

#52 fix: missing import and definition in callback
  src/pages/Login/Login.tsx
Labels: bug

#53 bug: solved issues for logout and added TODO comments
  src/shared/api/endpoints/security.ts
  src/utils/logout.ts
Labels: bug

#54 refactor: removed utils logout function
  src/components/AppBarMobile/AppBarMobile.tsx
  src/components/AppBarWeb/AppBarWeb.tsx
  src/components/Main/Main.spec.tsx
  src/components/Main/Main.tsx
  src/shared/api/endpoints/authentication.ts
  src/utils/logout.ts
Labels: refactor

#55 refactor: modified appbar to encapsulate functions such as login and logout
  src/components/AppBarMobile/AppBarMobile.spec.tsx
  src/components/AppBarMobile/AppBarMobile.spec.tsx.txt
  src/components/AppBarMobile/AppBarMobile.tsx
  src/components/AppBarMobile/stories/AppBarMobile.stories.tsx
  src/components/AppBarWeb/AppBarWeb.spec.tsx
  src/components/AppBarWeb/AppBarWeb.spec.tsx.txt
  src/components/AppBarWeb/AppBarWeb.tsx
  src/components/AppBarWeb/stories/AppBarWeb.stories.tsx
  src/components/Main/Main.spec.tsx.txt
  src/components/Main/Main.tsx
  src/components/TopBar/TopBar.spec.tsx
  src/components/TopBar/TopBar.tsx
Labels: refactor
